### ISSUE TITLE
[Android Bootcamp] Assignment 3: Twitter Client - Ready for review

### ISSUE THREAD

**Issue by cvijayarenu** [cvijayarenu/codepath-weekthree-twitterclient#1]
My app is ready for review. "/cc @codepathreview @codepath".  I have completed all the required tasks. I will work on the advanced task now and update it before sunday. but this is ready for review now. 

Thanks

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly
- Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
- Good to see you refreshed the timeline after composing a new tweet
-  Consider adding the character count for Compose Activity to limit to 140. See [this event handler](http://guides.codepath.com/android/Basic-Event-Listeners#textchangedlistener) for more details.
- Consider adding local persistence of tweets by using ActiveAndroid in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/ActiveAndroid-Guide) for more details.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
